### ISSUE TITLE
question on Generate /// docs in code generator in roadmap

### ISSUE THREAD

**Issue by jamessdixon** [fsprojects/Elmish.XamarinForms#152]
instead of using XML Code comments above each public function (which is what I assume "Generate /// docs in code generator" does) can we put them all in a separate file - so the code does not get so cluttered?

**Comment by dsyme** [comment]
@jamessdixon I generally prefer them in the same file, since there is no tooling support in F# in Visual Studio for having them in a separate file.  For the generated code I don't mind either way

The point of the work item is mostly to propagate docs from Xamarin.Forms.Core.dll/xml --> Xamarin.Forms.Core.fs, e.g. the "Label" static method in Xamarin.Forms.Core.fs could have an XML doc based on the one on the Label class in Xamarin.Forms.Core.dll/xml , and even more importantly for all the various optional parameters

**Comment by jamessdixon** [comment]
@dsyme do you mean the 200+ members in here?  You want XmlCodeComments for them> 

https://github.com/fsprojects/Elmish.XamarinForms/blob/master/Elmish.XamarinForms/Xamarin.Forms.Core.fs

**Comment by dsyme** [comment]
Yes, I was thinking we could auto-generate them from the content available in `Xamarin.Forms.Core.xml`.  It's a bit painful though, sorry :)

**Comment by dsyme** [comment]
Closing question (still would be great to have this done!)
