### ISSUE TITLE
Performance problems on Android with ScrollView containing Grid children

### ISSUE THREAD

**Issue by kevinha** [fsprojects/Elmish.XamarinForms#160]
I have been developing an app that has a ScrollView containing Grid children comprising Label and Image views. The Grid children contain un/expand Images that control whether a further Label is displayed, kinda like this:

![image](https://user-images.githubusercontent.com/23430/44136976-abadb0dc-a066-11e8-9478-df2bf0386e73.png)

Performance is ok for children at the bottom of the ScrollView but it deteriorates the closer the child is to the top of the ScrollView to the extent that it is not acceptable. From the 3rd from bottom child warnings are generated about work being performed on the main thread:

08-15 07:40:14.637 13474 13474 I Choreographer: Skipped 37 frames!  The application may be doing too much work on its main thread.

and it gets worse for children at the top of the ScrollView:

08-15 07:44:16.308 13474 13474 I Choreographer: Skipped 174 frames!  The application may be doing too much work on its main thread.

The view function has negligible performance impact so I assume the problem is in the view diffing. GCs seem more frequent as well. I'm new to Xamarin so the layout may not be optimal but I don't think it is that complex. Repro zip to follow.

**Comment by kevinha** [comment]
[ScrollGridRepro.zip](https://github.com/fsprojects/Elmish.XamarinForms/files/2289645/ScrollGridRepro.zip)

Bitbucket repo available as well, if required.

**Comment by TimLariviere** [comment]
@kevinha I'm not sure the view diffing is the culprit here.
I see that your repro uses a lot of `GridLength.Auto` for columns and rows.
Generally "auto" sizing can rapidly make your app stutter, as this needs a lot of layout calculation.

From MSDN
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/deploy-test/performance
>When using a Grid, try to ensure that as few rows and columns as possible are set to Auto size. Each auto-sized row or column will cause the layout engine to perform additional layout calculations. Instead, use fixed size rows and columns if possible. Alternatively, set rows and columns to occupy a proportional amount of space with the GridUnitType.Star enumeration value, provided that the parent tree follows these layout guidelines.

One way to fix your performance problem could be to define 2 fixed sizes: 1 for collapsed state, 1 for expanded state. This limits your options but it's definitely better for the UI (and will be easier to add virtualization later).

**Comment by kevinha** [comment]
That makes sense as layout recalculation would be more expensive the further up the list and dovetails nicely with my Xamarin ignorance. Will close. Thanks @TimLariviere.
